server:
  port: 7000

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PioneerR/okr.git

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@eureka:8000/eureka,http://admin:123456@eureka2:8001/eureka
  instance:
    prefer-ip-address: true # 在地址栏上使用IP地址进行显示
    instance-id: config