server:
 port: 8090

spring:
 application:
   name: relation-user

eureka:
  client:
    register-with-eureka: true
    # 客户端拉取服务注册信息间隔，默认30秒
    registry-fetch-interval-seconds: 30
    service-url:
      #      defaultZone: http://admin:123456@127.0.0.1:8000/eureka # 此处的admin:123456是SpringSecurity的账号密码
      defaultZone: http://admin:123456@eureka:8000/eureka,http://admin:123456@eureka2:8001/eureka
  instance:
    instance-id: relation-user               # 页面中的status值
    prefer-ip-address: true                  # 客户端在注册时使用自己的ip而不是主机名，默认false
    # 心跳检查
    lease-renewal-interval-in-seconds: 2     # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5  # 如果现在超过了5秒的间隔（默认是90秒）

info:
  app.name: relation-user
  company.name: com.xc
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$

# HystrixDashboard - 监控 - 开启所有端口（springboot2以上）
management:
  endpoints:
    web:
      exposure:
        include: '*'