spring:
  profiles:
    active:
      - dev
---
server:
  port: 7010

spring:
  profiles: dev
  application:
    name: config-client-dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@eureka:8000/eureka,http://admin:123456@eureka2:8001/eureka
    register-with-eureka: false

info:
  app.name: config-client-dev
  company.name: com.xc.dev
---
server:
  port: 7011

spring:
  profiles: pro
  application:
    name: config-client-pro

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@eureka:8000/eureka,http://admin:123456@eureka2:8001/eureka
    register-with-eureka: false

info:
  app.name: config-client-pro
  company.name: com.xc.pro