server:
  port: 80

#ribbon:
#  eureka:
#    enabled: false
#
#RELATION-PRO:
#  ribbon:
#    listOfServers: http://eureka:8080,http://eureka2:8081


eureka:
  client:
    register-with-eureka: false
    service-url:
        defaultZone: http://admin:123456@eureka:8000/eureka,http://admin:123456@eureka2:8001/eureka