server:
  port: 80

eureka:
  client:
    fetch-registry: true          # 服务消费者需要获取注册表，进行消费
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:123456@eureka:8000/eureka/,http://admin:123456@eureka2:8001/eureka/