spring:
  profiles:
    active: native
  application:
    name: config
  cloud:
    config:
      server:
        native:
          search-locations: file:./config-repo
        default-label: master
#        git:
#          uri:
#          search-paths: config-repo
#          username: dailybuild
#          password: dailybuild2018

server:
  port: 8001

info:
  name: ${spring.application.name}

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: ${eureka.uri:http://127.0.0.1:8000/eureka}
    healthcheck:
      enabled: true

service:
  static:
    location: config-repo

security:
  user:
    name: xcokr
    password: xcokr