server:
  port: 8081

mybatis:
  mapper-locations: # 所有的mapper映射文件
    - classpath:mapping/*.xml

spring:
  application:
    name: relation-pro2
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.jdbc.Driver     # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/relation2?serverTimezone=GMT%2B8 # 数据库连接地址
    username: root # 数据库用户名
    password: 123456 # 数据库连接密码
  security:
    user:
      name: admin  # 认证用户名
      password: 123456  # 认证密码
      roles:
        - USER # 授权角色

eureka:
  client:
    register-with-eureka: true
    # 客户端拉取服务注册信息间隔，默认30秒
    registry-fetch-interval-seconds: 30
    service-url:
#      defaultZone: http://admin:123456@127.0.0.1:8000/eureka # 此处的admin:123456是SpringSecurity的账号密码
      defaultZone: http://admin:123456@eureka:8000/eureka/,http://admin:123456@eureka2:8001/eureka/

  instance:
    instance-id: relation-pro2               # 页面中的status值
    prefer-ip-address: true                  # 客户端在注册时使用自己的ip而不是主机名，默认false
    # 心跳检查
    lease-renewal-interval-in-seconds: 2     # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5  # 如果现在超过了5秒的间隔（默认是90秒）


# 监控的配置：健康检查
info:
  app.name: relation-pro2
  company.name: enjoy
  build.artifactId: $project.artifactId$ # 父pom有对$进行解析的插件plugins的配置
  build.modelVersion: $project.modelVersion$

