# 服务端口
server:
  port: 8000

# 指定生效的配置文件
spring:
  application:
    name: eureka # 服务名
  profiles:
    active: native # 服务启动时，制定profiles配置使用单机配置 或 集群配置

# 日志配置文件
logging:
  config: classpath:logback-spring.xml

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: 127.0.0.1

## eureka - 单机注册中心配置
#---
#spring:
#  profiles: native
#server:
#  port: 8000
#info:
#  name: ${spring.application.name}
#
#eureka:
#  server:
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 5000
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url: http://${eureka.instance.hostname}:${server.port}/eureka/
#  instance:
#    hostname: 127.0.0.1